
// Generated by Cadence Encounter(R) RTL Compiler RC14.13 - v14.10-s027_1

// Verification Directory fv/vehicleControl 

module vehicleControl(clock, _switch, _turnShift, _gearShift,
     _turnState, _gearState);
  input clock, _switch;
  input [1:0] _turnShift, _gearShift;
  output [1:0] _turnState, _gearState;
  wire clock, _switch;
  wire [1:0] _turnShift, _gearShift;
  wire [1:0] _turnState, _gearState;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  assign _turnState[0] = _turnState[1];
  DFFSNQ_X1 \_turnState_reg[0] (.SN (1'b1), .CLK (clock), .D (n_12), .Q
       (_turnState[1]));
  DFFSNQ_X1 \_gearState_reg[0] (.SN (1'b1), .CLK (clock), .D (n_11), .Q
       (_gearState[0]));
  NOR2_X1 g369(.A1 (n_9), .A2 (n_10), .ZN (n_12));
  DFFSNQ_X1 \_gearState_reg[1] (.SN (1'b1), .CLK (clock), .D (n_8), .Q
       (_gearState[1]));
  AOI21_X1 g370(.A1 (n_5), .A2 (n_3), .B (n_10), .ZN (n_11));
  AOI21_X1 g372(.A1 (n_6), .A2 (_turnShift[1]), .B (n_7), .ZN (n_9));
  NOR2_X1 g371(.A1 (n_4), .A2 (n_10), .ZN (n_8));
  OAI22_X1 g375(.A1 (n_6), .A2 (_turnShift[1]), .B1 (n_1), .B2
       (_turnShift[0]), .ZN (n_7));
  AOI21_X1 g373(.A1 (_gearShift[1]), .A2 (_gearShift[0]), .B (n_2), .ZN
       (n_5));
  AOI22_X1 g374(.A1 (n_3), .A2 (_gearShift[0]), .B1 (_gearState[1]),
       .B2 (_gearShift[1]), .ZN (n_4));
  AOI21_X1 g376(.A1 (n_0), .A2 (_gearShift[1]), .B (_gearShift[0]), .ZN
       (n_2));
  NAND2_X1 g377(.A1 (n_1), .A2 (_turnShift[0]), .ZN (n_6));
  OR2_X1 g378(.A1 (_gearState[1]), .A2 (_gearState[0]), .Z (n_3));
  INV_X1 g380(.I (_gearState[0]), .ZN (n_0));
  INV_X1 g379(.I (_turnState[1]), .ZN (n_1));
  INV_X1 g381(.I (_switch), .ZN (n_10));
endmodule

